use std::collections::BTreeMap;

use dioxus::prelude::*;
use wasm_bindgen::JsValue;

use crate::agent::{self, ThreadMessage, ThreadRole};
use crate::api;
use crate::catalog::CatalogExplorer;
use crate::chat_view::normalize_trace_view;
use crate::components::{parse_rich_blocks, DataTable, RichBlock, TrajectoryView};
use crate::copilot_sessions::{
    can_start_new_chat, delete_session, empty_thread, load_index, load_session_thread,
    new_session_id, now_millis, page_after_history_switch, persist_indexed_thread, relative_time,
    restore_for_run, save_index, session_storage_key, title_from_thread, AssistantSessionMeta,
    BrowserStore, KvStore,
};
use crate::llm;
use crate::llm_settings::LlmSettings;
use crate::model::{
    CatalogTree, DimensionAggregate, EventProvenance, HistogramBucket, QueryCatalog,
    QueryDatasetSummary, RunAnalysis, RunExplorerItem, RunPage, RunSummary, StorylineSnapshot,
    ToolAggregate, TurnDetail, TurnSummary,
};
use crate::terminology::{ANALYSIS, ASSISTANT, DATASETS, RUNS, STEPS, STORAGE, TIMELINE};

#[derive(Clone, Debug, PartialEq)]
struct WorkspaceNotice {
    title: String,
    summary: String,
    detail: String,
    turn_id: Option<i64>,
}

fn workspace_notice(detail: String) -> WorkspaceNotice {
    WorkspaceNotice {
        title: "Workspace request failed".into(),
        summary: detail
            .lines()
            .next()
            .unwrap_or("Request failed")
            .to_string(),
        detail,
        turn_id: None,
    }
}

fn evidence_notice(turn_id: i64, detail: &str) -> WorkspaceNotice {
    WorkspaceNotice {
        title: "Step details could not be decoded".into(),
        summary: format!("Step #{turn_id} · {}", type_mismatch_summary(detail)),
        detail: detail.to_string(),
        turn_id: Some(turn_id),
    }
}

fn type_mismatch_summary(detail: &str) -> String {
    let received = detail
        .split("invalid type: ")
        .nth(1)
        .and_then(|rest| rest.split([',', ' ']).next())
        .filter(|value| !value.is_empty());
    let expected = detail
        .split("expected a ")
        .nth(1)
        .and_then(|rest| rest.split_whitespace().next())
        .map(|value| value.trim_end_matches(['.', ',']));
    match (expected, received) {
        (Some(expected), Some(received)) => format!("Expected {expected}, received {received}"),
        _ => "The step data did not match the expected format".into(),
    }
}

struct RunFilters {
    query: String,
    dataset: String,
    status: String,
    sort: String,
    direction: String,
    path: String,
    file: String,
    offset: usize,
}

pub fn App() -> Element {
    let initial_agent = url_param("agent_id");
    let initial_session = url_param("session_id");
    let initial_root = url_param("root_session_id");
    // Keep missing Catalog coordinates empty so legacy deep links can still be
    // resolved when the selected Storyline is unambiguous. Once the run list
    // loads, links generated by the current UI always carry the full key.
    let initial_dataset = url_param("dataset").unwrap_or_default();
    let initial_file = url_param("file").unwrap_or_default();
    let initial_run_id = url_param("run_id").filter(|value| !value.is_empty());
    let initial_run = initial_agent
        .zip(initial_session)
        .map(|(agent_id, session_id)| RunSummary {
            dataset: initial_dataset,
            file: initial_file,
            run_id: initial_run_id,
            agent_id,
            model_name: None,
            session_id,
            root_session_id: initial_root,
            path: String::new(),
            row_count: 0,
            duplicate_event_ids: 0,
            status: "loading".into(),
        });
    let initial_analysis_session_id = url_param("analysis_session").unwrap_or_default();
    let initial_analysis_seed_scope = if initial_analysis_session_id.is_empty() {
        web_sys::window()
            .and_then(|window| window.location().search().ok())
            .and_then(|search| crate::analysis_session::scope_from_query(&search).ok())
    } else {
        None
    };
    let initial_page = if initial_run.is_some() {
        "detail"
    } else {
        match url_param("page").as_deref() {
            Some("tools") => "tools",
            Some("runs") => "runs",
            Some("physical") => "physical",
            _ => "catalog",
        }
    };
    let mut page = use_signal(move || initial_page.to_string());
    let runs = use_signal(|| None::<RunPage>);
    let runs_loading = use_signal(|| true);
    let mut query = use_signal(|| url_param("q").unwrap_or_default());
    let mut dataset_filter =
        use_signal(|| url_param("dataset_filter").unwrap_or_else(|| "all".into()));
    let mut status = use_signal(|| url_param("status").unwrap_or_else(|| "all".into()));
    let mut sort = use_signal(|| url_param("sort").unwrap_or_else(|| "session".into()));
    let mut direction = use_signal(|| url_param("direction").unwrap_or_else(|| "asc".into()));
    let mut run_path = use_signal(|| url_param("path").unwrap_or_default());
    let mut file_prefix = use_signal(|| url_param("file_prefix").unwrap_or_default());
    let mut catalog_dataset = use_signal(|| String::new());
    let mut catalog_prefix = use_signal(|| String::new());
    let catalog_tree = use_signal(|| None::<CatalogTree>);
    let catalog_loading = use_signal(|| false);
    let mut offset = use_signal(|| 0usize);
    let mut error = use_signal(|| None::<WorkspaceNotice>);

    let mut selected_run = use_signal(move || initial_run);
    let mut analysis = use_signal(|| None::<RunAnalysis>);
    let mut turns = use_signal(Vec::<TurnSummary>::new);
    let mut selected_turn = use_signal(|| None::<TurnDetail>);
    let mut expanded_turn_id =
        use_signal(|| url_param("turn").and_then(|value| value.parse::<i64>().ok()));
    let mut storyline = use_signal(|| None::<StorylineSnapshot>);
    let detail_loading = use_signal(|| false);
    let turn_loading = use_signal(|| false);
    let mut detail_mode = use_signal(|| url_param("workspace").unwrap_or_else(|| "trace".into()));
    let mut trace_mode = use_signal(|| {
        normalize_trace_view(&url_param("view").unwrap_or_else(|| "chats".into())).to_string()
    });
    let mut source = use_signal(|| url_param("source").unwrap_or_else(|| "all".into()));
    let mut turn_query = use_signal(|| url_param("turn_q").unwrap_or_default());

    let mut catalog = use_signal(|| None::<QueryCatalog>);
    let mut selected_table = use_signal(String::new);
    let mut copilot_open = use_signal(|| false);
    let mut copilot_wide = use_signal(load_copilot_wide);
    let mut analysis_session_id = use_signal(move || initial_analysis_session_id);
    let mut analysis_seed_scope = use_signal(move || initial_analysis_seed_scope);

    use_effect(move || {
        load_runs(
            RunFilters {
                query: query(),
                dataset: dataset_filter(),
                status: status(),
                sort: sort(),
                direction: direction(),
                path: run_path(),
                file: file_prefix(),
                offset: offset(),
            },
            runs,
            runs_loading,
            error,
        );
    });

    use_effect(move || {
        if page() != "catalog" {
            return;
        }
        load_catalog_tree(
            catalog_dataset(),
            catalog_prefix(),
            catalog_tree,
            catalog_loading,
            error,
        );
    });

    use_effect(move || {
        if analysis().is_none() {
            if let Some(run) = selected_run() {
                load_workspace(run, analysis, turns, storyline, detail_loading, error);
            }
        }
    });

    use_effect(move || {
        if analysis().is_some() && selected_turn().is_none() {
            if let (Some(run), Some(turn_id)) = (
                selected_run(),
                url_param("turn").and_then(|value| value.parse::<i64>().ok()),
            ) {
                load_turn(
                    run,
                    turn_id,
                    expanded_turn_id,
                    selected_turn,
                    turn_loading,
                    error,
                );
            }
        }
    });

    use_effect(move || {
        sync_workspace_url(
            &page(),
            &analysis_session_id(),
            analysis_seed_scope().is_some(),
            selected_run().as_ref(),
            &query(),
            &dataset_filter(),
            &status(),
            &sort(),
            &direction(),
            &run_path(),
            &file_prefix(),
            &detail_mode(),
            &trace_mode(),
            &source(),
            &turn_query(),
            expanded_turn_id(),
        );
    });

    use_effect(move || {
        if catalog().is_none() {
            spawn(async move {
                match api::query_catalog().await {
                    Ok(value) => {
                        if selected_table().is_empty() {
                            selected_table.set(
                                value
                                    .tables
                                    .first()
                                    .map(|table| table.name.clone())
                                    .unwrap_or_default(),
                            );
                        }
                        catalog.set(Some(value));
                    }
                    Err(message) => error.set(Some(workspace_notice(message))),
                }
            });
        }
    });

    let root_keydown = move |event: KeyboardEvent| {
        let key = event.key().to_string().to_ascii_lowercase();
        if key == "j" && (event.modifiers().meta() || event.modifiers().ctrl()) {
            event.prevent_default();
            copilot_open.set(!copilot_open());
        }
    };

    rsx! {
        div { class: "pc2-shell", tabindex: "-1", onkeydown: root_keydown,
            a { class: "skip-link", href: "#pc2-main", "Skip to main content" }
            nav { class: "rail", aria_label: "pChronicle navigation",
                div { class: "brand-mark", title: "pChronicle", "pC" }
                RailButton { active: page() == "catalog", icon: "▣", label: DATASETS, onclick: move |_| { catalog_dataset.set(String::new()); catalog_prefix.set(String::new()); page.set("catalog".into()); } }
                RailButton { active: page() == "runs" || page() == "detail", icon: "◫", label: RUNS, onclick: move |_| page.set("runs".into()) }
                RailButton { active: page() == "tools", icon: "⌁", label: ANALYSIS, onclick: move |_| page.set("tools".into()) }
                RailButton { active: page() == "physical", icon: "▤", label: STORAGE, onclick: move |_| page.set("physical".into()) }
                div { class: "rail-spacer" }
                button { class: if copilot_open() { "rail-button active" } else { "rail-button" }, aria_label: "Toggle Assistant", onclick: move |_| copilot_open.set(!copilot_open()), span { class: "rail-icon", "◇" } span { {ASSISTANT} } }
                div { class: "rail-status", span { class: "live-dot" } "Local" }
            }

            main { id: "pc2-main", class: "pc2-main", tabindex: "-1",
                if let Some(notice) = error() {
                    div { class: "pc2-workspace-notice", role: "alert",
                        div { class: "pc2-workspace-notice-copy",
                            strong { "{notice.title}" }
                            span { "{notice.summary}" }
                            details { class: "pc2-workspace-notice-details",
                                summary { "Show technical details" }
                                pre { "{notice.detail}" }
                            }
                        }
                        button { aria_label: "Dismiss", onclick: move |_| error.set(None), "×" }
                    }
                }
                match page().as_str() {
                    "catalog" => rsx! {
                        CatalogExplorer {
                            tree: catalog_tree(),
                            loading: catalog_loading(),
                            on_open: move |(dataset, prefix): (String, String)| {
                                catalog_dataset.set(dataset);
                                catalog_prefix.set(prefix);
                            },
                            on_runs: move |(dataset, prefix): (String, String)| {
                                dataset_filter.set(if dataset.is_empty() { "all".into() } else { dataset });
                                file_prefix.set(prefix);
                                run_path.set(String::new());
                                offset.set(0);
                                page.set("runs".into());
                            },
                        }
                    },
                    "physical" => rsx! { crate::physical::PhysicalWorkspace {} },
                    "tools" => rsx! {
                        crate::analysis::AnalysisWorkspace {
                            catalog: catalog(),
                            initial_scope: analysis_seed_scope(),
                            requested_session_id: (!analysis_session_id().is_empty()).then(|| analysis_session_id()),
                            on_session_change: move |session_id: String| {
                                analysis_session_id.set(session_id);
                                analysis_seed_scope.set(None);
                            },
                        }
                    },
                    "detail" => {
                        let path_runs = runs().map(|page| page.path_index).unwrap_or_default();
                        let selected_path = analysis().map(|value| value.run.path).or_else(|| selected_run().map(|run| run.path)).unwrap_or_default();
                        rsx! { div { class: "pc2-detail-layout",
                            PathExplorer { runs: path_runs, selected_path, loading: runs_loading(), filter_folders: false,
                                on_path: move |value| { run_path.set(value); offset.set(0); page.set("runs".into()); },
                                on_select: move |run: RunSummary| { selected_run.set(Some(run)); analysis.set(None); turns.set(Vec::new()); selected_turn.set(None); expanded_turn_id.set(None); storyline.set(None); },
                            }
                            if let (Some(_run), Some(value)) = (selected_run(), analysis()) {
                                RunDetailWorkspace {
                                    run: value.run.clone(),
                                    analysis: value,
                                    turns: turns(),
                                    selected: selected_turn(),
                                    storyline: storyline(),
                                    expanded_turn_id: expanded_turn_id(),
                                    loading: detail_loading(),
                                    turn_loading: turn_loading(),
                                    detail_mode: detail_mode(),
                                    view: trace_mode(),
                                    source: source(),
                                    query: turn_query(),
                                    on_back: move |_| page.set("runs".into()),
                                    on_detail_mode: move |value| detail_mode.set(value),
                                    on_view: move |value: String| {
                                        trace_mode.set(normalize_trace_view(&value).to_string());
                                    },
                                    on_source: move |value| source.set(value),
                                    on_query: move |value| turn_query.set(value),
                                    on_apply_filter: move |_| {},
                                    on_turn: move |id| {
                                        if expanded_turn_id() == Some(id) {
                                            expanded_turn_id.set(None);
                                            selected_turn.set(None);
                                        } else if let Some(run) = selected_run() {
                                            expanded_turn_id.set(Some(id));
                                            selected_turn.set(None);
                                            load_turn(run, id, expanded_turn_id, selected_turn, turn_loading, error);
                                        }
                                    },
                                    on_open_copilot: move |_| copilot_open.set(true),
                                    on_analyze: move |run: RunSummary| {
                                        let Some(active_catalog) = catalog() else { return; };
                                        analysis_session_id.set(String::new());
                                        analysis_seed_scope.set(Some(run_analysis_scope(&active_catalog, run)));
                                        page.set("tools".into());
                                    },
                                }
                            } else { LoadingWorkspace { label: "Loading run details…" } }
                        } }
                    }
                    _ => {
                        let path_runs = runs().map(|value| value.path_index).unwrap_or_default();
                        rsx! { div { class: "pc2-runs-layout",
                        PathExplorer { runs: path_runs, selected_path: run_path(), loading: runs_loading(), filter_folders: true,
                            on_path: move |value| { run_path.set(value); offset.set(0); },
                            on_select: move |run: RunSummary| { selected_run.set(Some(run)); analysis.set(None); turns.set(Vec::new()); selected_turn.set(None); expanded_turn_id.set(None); detail_mode.set("trace".into()); page.set("detail".into()); },
                        }
                        RunsExplorer {
                            page: runs(),
                            loading: runs_loading(),
                            query: query(),
                            status: status(),
                            sort: sort(),
                            direction: direction(),
                            path: run_path(),
                            file: file_prefix(),
                            datasets: catalog().map(|value| value.datasets).unwrap_or_default(),
                            dataset: dataset_filter(),
                            on_query: move |value| query.set(value),
                            on_dataset: move |value| { dataset_filter.set(value); run_path.set(String::new()); file_prefix.set(String::new()); offset.set(0); },
                            on_status: move |value| status.set(value),
                            on_sort: move |value| sort.set(value),
                            on_direction: move |value| direction.set(value),
                            on_path: move |value| { run_path.set(value); offset.set(0); },
                            on_file: move |value| { file_prefix.set(value); offset.set(0); },
                            on_refresh: move |_| {
                                let filters = RunFilters {
                                        query: query(),
                                        dataset: dataset_filter(),
                                        status: status(),
                                        sort: sort(),
                                        direction: direction(),
                                        path: run_path(),
                                        file: file_prefix(),
                                        offset: offset(),
                                    };
                                spawn(async move {
                                    if let Err(message) = api::refresh_catalog().await {
                                        error.set(Some(workspace_notice(message)));
                                        return;
                                    }
                                    if let Ok(value) = api::query_catalog().await {
                                        catalog.set(Some(value));
                                    }
                                    load_runs(filters, runs, runs_loading, error);
                                });
                            },
                            on_page: move |value| offset.set(value),
                            on_select: move |run: RunSummary| {
                                selected_run.set(Some(run.clone()));
                                analysis.set(None);
                                turns.set(Vec::new());
                                selected_turn.set(None);
                                expanded_turn_id.set(None);
                                storyline.set(None);
                                detail_mode.set("trace".into());
                                page.set("detail".into());
                            },
                        }
                        } }
                    },
                }
            }

            if copilot_open() {
                    AssistantPanel {
                        run: selected_run(),
                        analysis: analysis(),
                        turns: turns(),
                        selected: selected_turn(),
                        wide: copilot_wide(),
                        on_toggle_wide: move |_| {
                            let next = !copilot_wide();
                            copilot_wide.set(next);
                            save_copilot_wide(next);
                        },
                        on_close: move |_| copilot_open.set(false),
                        on_turn: move |id| {
                            if let Some(run) = selected_run() {
                                expanded_turn_id.set(Some(id));
                                selected_turn.set(None);
                                load_turn(run, id, expanded_turn_id, selected_turn, turn_loading, error);
                                page.set("detail".into());
                            }
                        },
                        on_open_session: move |meta: AssistantSessionMeta| {
                            let next_page = page_after_history_switch(&page());
                            let changed = selected_run().as_ref().map(|run| run.query())
                                != Some(meta.run.query());
                            if changed {
                                if page() == "tools" {
                                    analysis_session_id.set(String::new());
                                    analysis_seed_scope.set(None);
                                }
                                selected_run.set(Some(meta.run.clone()));
                                analysis.set(None);
                                turns.set(Vec::new());
                                selected_turn.set(None);
                                expanded_turn_id.set(None);
                                storyline.set(None);
                            }
                            if page() != next_page {
                                page.set(next_page.to_string());
                            }
                        },
                    }
            }

        }
    }
}

fn load_runs(
    filters: RunFilters,
    mut page: Signal<Option<RunPage>>,
    mut loading: Signal<bool>,
    mut error: Signal<Option<WorkspaceNotice>>,
) {
    loading.set(true);
    spawn(async move {
        match api::explorer_runs(
            &filters.query,
            &filters.dataset,
            &filters.status,
            &filters.sort,
            &filters.direction,
            &filters.path,
            &filters.file,
            filters.offset,
        )
        .await
        {
            Ok(value) => page.set(Some(value)),
            Err(message) => error.set(Some(workspace_notice(message))),
        }
        loading.set(false);
    });
}

fn load_catalog_tree(
    dataset: String,
    prefix: String,
    mut tree: Signal<Option<CatalogTree>>,
    mut loading: Signal<bool>,
    mut error: Signal<Option<WorkspaceNotice>>,
) {
    loading.set(true);
    spawn(async move {
        match api::explorer_tree(&dataset, &prefix).await {
            Ok(value) => tree.set(Some(value)),
            Err(message) => error.set(Some(workspace_notice(message))),
        }
        loading.set(false);
    });
}

fn load_workspace(
    run: RunSummary,
    mut analysis: Signal<Option<RunAnalysis>>,
    mut turns: Signal<Vec<TurnSummary>>,
    mut storyline: Signal<Option<StorylineSnapshot>>,
    mut loading: Signal<bool>,
    mut error: Signal<Option<WorkspaceNotice>>,
) {
    loading.set(true);
    spawn({
        let run = run.clone();
        async move {
            let (next_analysis, next_turns) =
                futures_util::join!(api::run_analysis(&run), api::turns(&run, "", "all"),);
            match (next_analysis, next_turns) {
                (Ok(next_analysis), Ok(next_turns)) => {
                    analysis.set(Some(next_analysis));
                    turns.set(next_turns.records);
                }
                (Err(message), _) | (_, Err(message)) => {
                    error.set(Some(workspace_notice(message)));
                }
            }
            loading.set(false);
        }
    });
    // The storyline powers context reconstruction in the turn inspector. It is
    // additive and can be slow to project, so it loads independently: it must
    // neither block nor blank the workspace.
    spawn(async move {
        if let Ok(snapshot) = api::storyline(&run).await {
            storyline.set(Some(snapshot));
        }
    });
}

fn load_turn(
    run: RunSummary,
    id: i64,
    active: Signal<Option<i64>>,
    mut selected: Signal<Option<TurnDetail>>,
    mut loading: Signal<bool>,
    mut error: Signal<Option<WorkspaceNotice>>,
) {
    loading.set(true);
    spawn(async move {
        match api::turn_detail(&run, id).await {
            Ok(value) if active() == Some(id) => selected.set(Some(value)),
            Ok(_) => {}
            Err(message) if active() == Some(id) => error.set(Some(evidence_notice(id, &message))),
            Err(_) => {}
        }
        if active() == Some(id) {
            loading.set(false);
        }
    });
}

#[component]
fn RailButton(
    active: bool,
    icon: &'static str,
    label: &'static str,
    onclick: EventHandler<MouseEvent>,
) -> Element {
    rsx! { button { class: if active { "rail-button active" } else { "rail-button" }, aria_current: if active { "page" } else { "false" }, onclick, span { class: "rail-icon", "{icon}" } span { "{label}" } } }
}

#[component]
fn LoadingWorkspace(label: &'static str) -> Element {
    rsx! { div { class: "pc2-loading", span { class: "spinner" } "{label}" } }
}

#[derive(Clone, Debug, Default, PartialEq)]
struct PathTreeNode {
    name: String,
    full_path: String,
    children: BTreeMap<String, PathTreeNode>,
    runs: Vec<RunSummary>,
}

fn build_path_tree(runs: &[RunSummary]) -> PathTreeNode {
    let mut root = PathTreeNode {
        name: "All runs".into(),
        ..PathTreeNode::default()
    };
    for run in runs {
        let segments = run
            .path
            .split('/')
            .filter(|value| !value.is_empty())
            .collect::<Vec<_>>();
        let mut node = &mut root;
        let mut current = String::new();
        for segment in segments {
            if !current.is_empty() {
                current.push('/');
            }
            current.push_str(segment);
            node = node
                .children
                .entry(segment.into())
                .or_insert_with(|| PathTreeNode {
                    name: segment.into(),
                    full_path: current.clone(),
                    ..PathTreeNode::default()
                });
        }
        node.runs.push(run.clone());
    }
    root
}

fn subtree_run_count(node: &PathTreeNode) -> usize {
    node.runs.len() + node.children.values().map(subtree_run_count).sum::<usize>()
}

#[component]
fn PathExplorer(
    runs: Vec<RunSummary>,
    selected_path: String,
    loading: bool,
    filter_folders: bool,
    on_path: EventHandler<String>,
    on_select: EventHandler<RunSummary>,
) -> Element {
    let tree = build_path_tree(&runs);
    rsx! { aside { class: "pc2-path-explorer",
        header { div { strong { "Run paths" } span { "Browse runs by source hierarchy" } } span { "{runs.len()}" } }
        div { class: "pc2-path-tree",
            button { class: if selected_path.is_empty() { "pc2-path-all active" } else { "pc2-path-all" }, onclick: move |_| on_path.call(String::new()), span { class: "pc2-path-icon root", "⌂" } strong { "All runs" } code { "{runs.len()}" } }
            if loading && runs.is_empty() { div { class: "pc2-path-loading", span { class: "spinner" } "Loading paths…" } }
            else if runs.is_empty() { div { class: "pc2-path-empty", "No captured run paths." } }
            else { for node in tree.children.into_values() { PathNode { key: "{node.full_path}", node, selected_path: selected_path.clone(), filter_folders, on_path, on_select } } }
        }
        footer { "Folders follow agent / root / subagent / session coordinates." }
    } }
}

#[component]
fn PathNode(
    node: PathTreeNode,
    selected_path: String,
    filter_folders: bool,
    on_path: EventHandler<String>,
    on_select: EventHandler<RunSummary>,
) -> Element {
    let count = subtree_run_count(&node);
    let is_leaf = node.children.is_empty() && node.runs.len() == 1;
    if is_leaf {
        let run = node.runs[0].clone();
        let active = selected_path == run.path;
        let tone = match run.status.as_str() {
            "completed" | "ok" => "good",
            "active" => "live",
            "failed" | "error" => "bad",
            _ => "",
        };
        return rsx! { button { class: if active { "pc2-path-row active" } else { "pc2-path-row" }, title: "{run.path}", onclick: move |_| on_select.call(run.clone()), span { class: "pc2-path-toggle leaf" } span { class: "pc2-path-name", span { class: "pc2-path-icon run" } span { "{node.name}" } } span { class: "pc2-path-health {tone}" } code { "1" } } };
    }
    let folder_path = node.full_path.clone();
    rsx! { details { open: true,
        summary { class: if selected_path == node.full_path { "pc2-path-row branch active" } else { "pc2-path-row branch" }, span { class: "pc2-path-toggle", "›" } button { class: "pc2-path-name", onclick: move |event| { if filter_folders { event.prevent_default(); on_path.call(folder_path.clone()); } }, span { class: "pc2-path-icon folder" } span { "{node.name}" } } span {} code { "{count}" } }
        div { class: "pc2-path-children",
            for run in node.runs { button { class: if selected_path == run.path { "pc2-path-row active" } else { "pc2-path-row" }, onclick: move |_| on_select.call(run.clone()), span { class: "pc2-path-toggle leaf" } span { class: "pc2-path-name", span { class: "pc2-path-icon run" } span { "{run.session_id}" } } span {} code { "1" } } }
            for child in node.children.into_values() { PathNode { key: "{child.full_path}", node: child, selected_path: selected_path.clone(), filter_folders, on_path, on_select } }
        }
    } }
}

#[component]
fn RunsExplorer(
    page: Option<RunPage>,
    loading: bool,
    query: String,
    datasets: Vec<QueryDatasetSummary>,
    dataset: String,
    status: String,
    sort: String,
    direction: String,
    path: String,
    file: String,
    on_query: EventHandler<String>,
    on_dataset: EventHandler<String>,
    on_status: EventHandler<String>,
    on_sort: EventHandler<String>,
    on_direction: EventHandler<String>,
    on_path: EventHandler<String>,
    on_file: EventHandler<String>,
    on_refresh: EventHandler<MouseEvent>,
    on_page: EventHandler<usize>,
    on_select: EventHandler<RunSummary>,
) -> Element {
    let total = page.as_ref().map_or(0, |page| page.snapshot.total);
    let page_offset = page.as_ref().map_or(0, |page| page.snapshot.offset);
    let page_limit = page.as_ref().map_or(50, |page| page.snapshot.limit);
    let page_next = page.as_ref().map_or(0, |page| page.snapshot.next_offset);
    let page_has_more = page.as_ref().is_some_and(|page| page.snapshot.has_more);
    rsx! {
        section { class: "pc2-page",
            header { class: "pc2-page-head",
                div { p { class: "eyebrow", "pChronicle" } h1 { "Runs" } p { "Inspect agent execution, latency, tool use, and failures." } }
                button { class: "button", onclick: on_refresh, "↻ Refresh" }
            }
            div { class: "pc2-filterbar",
                label { class: "pc2-filter-search", span { "⌕" } input { value: "{query}", placeholder: "Agent, session, root, or status", aria_label: "Search runs", oninput: move |event| on_query.call(event.value()) } }
                select { value: "{dataset}", aria_label: "Filter by Dataset", onchange: move |event| on_dataset.call(event.value()),
                    option { value: "all", "All Datasets" }
                    for mounted in datasets { option { value: "{mounted.name}", "{mounted.name}" } }
                }
                select { value: "{status}", aria_label: "Filter by run status", onchange: move |event| on_status.call(event.value()), option { value: "all", "All statuses" } option { value: "active", "Active" } option { value: "completed", "Completed" } option { value: "failed", "Failed" } }
                select { value: "{sort}", aria_label: "Sort runs", onchange: move |event| on_sort.call(event.value()), option { value: "session", "Session" } option { value: "events", "Events" } option { value: "status", "Status" } option { value: "agent", "Agent" } }
                button { class: "pc2-sort", aria_label: "Toggle sort direction", onclick: move |_| on_direction.call(if direction == "asc" { "desc".into() } else { "asc".into() }), if direction == "asc" { "↑ Asc" } else { "↓ Desc" } }
                if !path.is_empty() { button { class: "pc2-path-filter", title: "{path}", onclick: move |_| on_path.call(String::new()), "⌁ {short(&path, 24)} ×" } }
                if !file.is_empty() { button { class: "pc2-path-filter", title: "{file}", onclick: move |_| on_file.call(String::new()), "_file_ {short(&file, 24)} ×" } }
                span { class: "pc2-result-count", "{total} runs" }
            }
            div { class: "pc2-table-wrap",
                table { class: "pc2-run-table",
                    thead { tr { th { "Session" } th { "Agent / model" } th { "Status" } th { "Events" } th { "Root" } } }
                    tbody {
                        if loading && page.is_none() {
                            for _ in 0..6 { tr { class: "pc2-table-skeleton", td { colspan: "5" } } }
                        } else if page.as_ref().is_none_or(|page| page.records.is_empty()) {
                            tr { td { colspan: "5", div { class: "pc2-empty", strong { "No matching runs" } span { "Adjust the filters or refresh the datasets." } } } }
                        } else {
                            for item in page.as_ref().unwrap().records.iter() {
                                RunTableRow { key: "{item.run.dataset}/{item.run.file}/{item.run.session_id}", item: item.clone(), on_select }
                            }
                        }
                    }
                }
            }
            if page.is_some() {
                footer { class: "pc2-pagination",
                    button { disabled: page_offset == 0, onclick: move |_| on_page.call(page_offset.saturating_sub(page_limit)), "← Previous" }
                    span { "{page_offset + usize::from(total > 0)}–{page_next} of {total}" }
                    button { disabled: !page_has_more, onclick: move |_| on_page.call(page_next), "Next →" }
                }
            }
        }
    }
}

#[component]
fn RunTableRow(item: RunExplorerItem, on_select: EventHandler<RunSummary>) -> Element {
    let run = item.run.clone();
    let keyboard_run = item.run.clone();
    let root_text = short(item.run.root_session_id.as_deref().unwrap_or("—"), 18);
    let model_text = item.model.clone().unwrap_or_else(|| "unavailable".into());
    rsx! {
        tr { tabindex: "0", onclick: move |_| on_select.call(run.clone()), onkeydown: move |event| if event.key() == Key::Enter { on_select.call(keyboard_run.clone()) },
            td { div { class: "pc2-session-cell", strong { "{item.run.session_id}" } span { "{item.run.row_count} captured rows" } } }
            td { div { class: "pc2-session-cell", strong { "{item.run.agent_id}" } span { "{model_text}" } } }
            td { StatusBadge { value: item.run.status.clone() } }
            td { class: "pc2-number", "{item.run.row_count}" }
            td { code { title: "{item.run.root_session_id.as_deref().unwrap_or_default()}", "{root_text}" } }
        }
    }
}

#[component]
fn StatusBadge(value: String) -> Element {
    let tone = match value.as_str() {
        "completed" | "ok" | "pass" => "good",
        "failed" | "error" | "fail" => "bad",
        "active" => "live",
        _ => "neutral",
    };
    rsx! { span { class: "pc2-status {tone}", span {} "{value}" } }
}

#[component]
#[allow(clippy::too_many_arguments)]
fn RunDetailWorkspace(
    run: RunSummary,
    analysis: RunAnalysis,
    turns: Vec<TurnSummary>,
    selected: Option<TurnDetail>,
    storyline: Option<StorylineSnapshot>,
    expanded_turn_id: Option<i64>,
    loading: bool,
    turn_loading: bool,
    detail_mode: String,
    view: String,
    source: String,
    query: String,
    on_back: EventHandler<MouseEvent>,
    on_detail_mode: EventHandler<String>,
    on_view: EventHandler<String>,
    on_source: EventHandler<String>,
    on_query: EventHandler<String>,
    on_apply_filter: EventHandler<()>,
    on_turn: EventHandler<i64>,
    on_open_copilot: EventHandler<MouseEvent>,
    on_analyze: EventHandler<RunSummary>,
) -> Element {
    let chats_active = view == "chats";
    let steps_active = view == "steps";
    let view_for_list = view.clone();
    let source_for_list = source.clone();
    let query_for_list = query.clone();
    rsx! {
        section { class: "pc2-detail",
            header { class: "pc2-detail-head",
                div { class: "pc2-detail-title", button { class: "pc2-back", onclick: on_back, "← Runs" } div { p { "{run.agent_id}" } h1 { title: "{run.session_id}", "{run.session_id}" } div { StatusBadge { value: run.status.clone() } if let Some(root) = &run.root_session_id { code { "root {short(root, 24)}" } } } } }
                div { class: "pc2-head-actions",
                    button { class: "button primary", onclick: on_open_copilot, "◇ Ask Assistant" }
                    button { class: "button", onclick: { let run = run.clone(); move |_| on_analyze.call(run.clone()) }, "Analyze this run" }
                    if analysis.event_provenance == EventProvenance::Canonical {
                        a { class: "button", href: "/api/export/otlp?{run.query()}", "OTLP" }
                    } else {
                        button { class: "button", disabled: true, title: "OTLP export requires recorded events", "OTLP unavailable · Reconstructed events" }
                    }
                }
            }
            MetricsStrip { analysis: analysis.clone() }
            if detail_mode == "trace" {
                CompactOverviewStrip {
                    analysis: analysis.clone(),
                    turns: turns.clone(),
                    on_open_analysis: move |_| on_detail_mode.call("analysis".into()),
                }
            }
            nav { class: "pc2-detail-tabs", aria_label: "Run detail view",
                button { class: if detail_mode == "trace" { "active" } else { "" }, onclick: move |_| on_detail_mode.call("trace".into()), {TIMELINE} }
                button { class: if detail_mode == "analysis" { "active" } else { "" }, onclick: move |_| on_detail_mode.call("analysis".into()), "Analysis" }
                span { "{turns.len()} of {analysis.turn_count} steps loaded for interactive charts" }
            }
            if detail_mode == "analysis" {
                AnalysisWorkspace {
                    analysis: analysis.clone(),
                    turns: turns.clone(),
                    on_turn: move |id| {
                        on_turn.call(id);
                        on_detail_mode.call("trace".into());
                    },
                }
            } else {
                section { class: "pc2-trace-surface pc2-inline-trace",
                    div { class: "pc2-trace-toolbar",
                        div { strong { if steps_active { "Steps" } else { "Conversations" } } span { "Bars show each step's place in the run · colors show type · sequence is not wall-clock time · expand a row for details" } }
                        div { class: "pc2-toolbar-controls",
                            div { class: "pc2-view-toggle", role: "group", aria_label: "Timeline layout",
                                button { class: if chats_active { "active" } else { "" }, onclick: move |_| on_view.call("chats".to_string()), "Conversations" }
                                button { class: if steps_active { "active" } else { "" }, onclick: move |_| on_view.call("steps".to_string()), {STEPS} }
                            }
                            select { value: "{source}", aria_label: "Filter steps by role", onchange: move |event| on_source.call(event.value()), option { value: "all", "All roles" } option { value: "user", "User" } option { value: "agent", "Agent" } option { value: "system", "System" } }
                            input { value: "{query}", placeholder: "Filter loaded steps", aria_label: "Filter steps", oninput: move |event| on_query.call(event.value()), onkeydown: move |event| if event.key() == Key::Enter { on_apply_filter.call(()) } }
                            button { class: "pc2-icon", aria_label: "Apply step filter", onclick: move |_| on_apply_filter.call(()), "⌕" }
                        }
                    }
                    div { class: "pc2-turn-list pc2-span-scroll",
                        if loading { div { class: "pc2-inline-loading", span { class: "spinner" } "Refreshing run details…" } }
                        if turns.is_empty() { div { class: "pc2-empty", strong { "No visible steps" } span { "No loaded steps match this filter." } } }
                        else { TrajectoryView { turns, expanded_turn_id, detail: selected, loading: turn_loading, context: storyline.map(|snapshot| snapshot.turns), view: view_for_list, source: source_for_list, query: query_for_list, on_turn } }
                    }
                }
            }
        }
    }
}

#[component]
fn MetricsStrip(analysis: RunAnalysis) -> Element {
    rsx! { div { class: "pc2-metrics",
        Metric { label: "Steps", value: analysis.turn_count.to_string(), detail: format!("{} {}", analysis.event_count, analysis.event_provenance.display_label().to_ascii_lowercase()) }
        Metric { label: "Tools", value: analysis.tool_call_count.to_string(), detail: format!("{} tool names", analysis.tools.len()) }
        Metric { label: "Explicit errors", value: analysis.error_count.to_string(), detail: "Captured signals only" }
        Metric { label: "Tokens", value: analysis.total_tokens.map(|value| value.to_string()).unwrap_or_else(|| "—".into()), detail: format!("in {} · out {}", optional_u64(analysis.prompt_tokens), optional_u64(analysis.completion_tokens)) }
        Metric { label: "Latency P95", value: analysis.latency_ms.p95.map(format_ms).unwrap_or_else(|| "—".into()), detail: format!("{}/{} samples", analysis.latency_ms.sample_count, analysis.latency_ms.total_count) }
    } }
}

#[component]
fn Metric(label: String, value: String, detail: String) -> Element {
    rsx! { div { class: "pc2-metric", span { "{label}" } strong { "{value}" } small { "{detail}" } } }
}

#[component]
fn CompactOverviewStrip(
    analysis: RunAnalysis,
    turns: Vec<TurnSummary>,
    on_open_analysis: EventHandler<MouseEvent>,
) -> Element {
    let sources = compact_mix(&analysis.source_breakdown, 3);
    let kinds = compact_mix(&analysis.kind_breakdown, 3);
    let models = compact_mix(&analysis.model_breakdown, 3);
    let coverage = coverage_points(
        analysis.latency_ms.sample_count,
        analysis.latency_ms.total_count,
        analysis.ttft_ms.sample_count,
        analysis.ttft_ms.total_count,
        turns.iter().filter(|turn| turn.timestamp.is_some()).count(),
        analysis.turn_count,
        turns
            .iter()
            .filter(|turn| turn.total_tokens.is_some())
            .count(),
        analysis.turn_count,
    );
    rsx! { div { class: "pc2-trace-overview",
        CompactMixCard { title: "Composition", tone: "blue", segments: sources, onclick: on_open_analysis }
        CompactMixCard { title: "Behavior", tone: "violet", segments: kinds, onclick: on_open_analysis }
        CompactMixCard { title: "Models", tone: "green", segments: models, onclick: on_open_analysis }
        CompactCoverageCard { points: coverage, onclick: on_open_analysis }
    } }
}

#[component]
fn CompactMixCard(
    title: &'static str,
    tone: &'static str,
    segments: Vec<MixSegment>,
    onclick: EventHandler<MouseEvent>,
) -> Element {
    let legend = segments.clone();
    let title_attr = mix_title(&segments);
    rsx! { button { class: "pc2-trace-overview-card", r#type: "button", aria_label: "Open Analysis overview · {title}", title: "Open Analysis for the full chart", onclick,
        span { class: "pc2-trace-overview-title", "{title}" }
        if segments.is_empty() {
            span { class: "pc2-trace-overview-empty", "No captured values" }
        } else {
            div { class: "pc2-mix-track {tone}", title: "{title_attr}",
                for segment in segments {
                    i { style: format!("width:{:.2}%", segment.share), title: format!("{} {}", segment.name, segment.count) }
                }
            }
            div { class: "pc2-mix-legend",
                for (index, segment) in legend.into_iter().enumerate() {
                    span { class: "pc2-mix-key {tone} n{index}", title: "{segment.name} {segment.count}", "{short(&segment.name, 16)} {segment.count}" }
                }
            }
        }
    } }
}

#[component]
fn CompactCoverageCard(points: Vec<CoveragePoint>, onclick: EventHandler<MouseEvent>) -> Element {
    rsx! { button { class: "pc2-trace-overview-card", r#type: "button", aria_label: "Open Analysis overview · Coverage", title: "Open Analysis for the full chart", onclick,
        span { class: "pc2-trace-overview-title", "Coverage" }
        div { class: "pc2-mini-coverage",
            for point in points {
                div { class: "pc2-mini-coverage-row",
                    span { "{point.label}" }
                    code { "{point.observed}/{point.total}" }
                    span { class: "pc2-coverage-track", i { style: format!("width:{:.2}%", percent(point.observed as f64, point.total as f64)) } }
                }
            }
        }
    } }
}

#[component]
fn AnalysisWorkspace(
    analysis: RunAnalysis,
    turns: Vec<TurnSummary>,
    on_turn: EventHandler<i64>,
) -> Element {
    let mut tab = use_signal(|| "overview".to_string());
    let active = tab();
    rsx! { section { class: "pc2-analysis-workspace",
        nav { class: "pc2-analysis-tabs", aria_label: "Analysis view",
            AnalysisTab { value: "overview", label: "Overview", active: active.clone(), on_select: move |value| tab.set(value) }
            AnalysisTab { value: "performance", label: "Performance", active: active.clone(), on_select: move |value| tab.set(value) }
            AnalysisTab { value: "tokens", label: "Tokens", active: active.clone(), on_select: move |value| tab.set(value) }
            AnalysisTab { value: "tools", label: "Tools", active: active.clone(), on_select: move |value| tab.set(value) }
        }
        div { class: "pc2-analysis-scroll",
            match active.as_str() {
                "performance" => rsx! { PerformanceAnalysis { analysis: analysis.clone(), turns: turns.clone(), on_turn } },
                "tokens" => rsx! { TokenAnalysis { analysis: analysis.clone(), turns: turns.clone(), on_turn } },
                "tools" => rsx! { ToolAnalysis { tools: analysis.tools.clone() } },
                _ => rsx! { OverviewAnalysis { analysis, turns } },
            }
        }
    } }
}

#[component]
fn AnalysisTab(
    value: &'static str,
    label: &'static str,
    active: String,
    on_select: EventHandler<String>,
) -> Element {
    rsx! { button { class: if active == value { "active" } else { "" }, onclick: move |_| on_select.call(value.into()), "{label}" } }
}

#[component]
fn OverviewAnalysis(analysis: RunAnalysis, turns: Vec<TurnSummary>) -> Element {
    let observed = turns.iter().filter(|turn| turn.timestamp.is_some()).count();
    let elapsed = match (&analysis.start_timestamp, &analysis.end_timestamp) {
        (Some(start), Some(end)) if start != end => format!("{start} → {end}"),
        (Some(start), _) => start.clone(),
        _ => "No captured timestamps".into(),
    };
    rsx! { div { class: "pc2-analysis-grid overview",
        AnalysisCard { title: "Execution composition", subtitle: "Steps grouped by recorded role",
            DimensionBars { items: analysis.source_breakdown.clone(), tone: "blue" }
        }
        AnalysisCard { title: "Behavior mix", subtitle: "Recorded step types",
            DimensionBars { items: analysis.kind_breakdown.clone(), tone: "violet" }
        }
        AnalysisCard { title: "Model mix", subtitle: "Model usage and coverage by step",
            DimensionBars { items: analysis.model_breakdown.clone(), tone: "green" }
        }
        AnalysisCard { title: "Data coverage", subtitle: "Available measurements and missing values",
            div { class: "pc2-coverage-list",
                CoverageRow { label: "Latency", observed: analysis.latency_ms.sample_count, total: analysis.latency_ms.total_count }
                CoverageRow { label: "TTFT", observed: analysis.ttft_ms.sample_count, total: analysis.ttft_ms.total_count }
                CoverageRow { label: "Timestamp", observed, total: analysis.turn_count }
                CoverageRow { label: "Token usage", observed: turns.iter().filter(|turn| turn.total_tokens.is_some()).count(), total: analysis.turn_count }
            }
        }
        article { class: "pc2-analysis-card wide pc2-run-span",
            header { div { h3 { "Captured run span" } p { "Lexically ordered source timestamps; unavailable values remain explicit" } } }
            code { "{elapsed}" }
            div { class: "pc2-run-span-meta",
                span { strong { "{analysis.models.len()}" } " models" }
                span { strong { "{analysis.event_count}" } " {analysis.event_provenance.display_label().to_ascii_lowercase()}" }
                span { strong { "{analysis.error_count}" } " steps with explicit errors" }
            }
        }
    } }
}

#[component]
fn PerformanceAnalysis(
    analysis: RunAnalysis,
    turns: Vec<TurnSummary>,
    on_turn: EventHandler<i64>,
) -> Element {
    let mut slowest = turns
        .iter()
        .filter_map(|turn| turn.latency_ms.map(|latency| (turn.clone(), latency)))
        .collect::<Vec<_>>();
    slowest.sort_by(|left, right| right.1.total_cmp(&left.1));
    slowest.truncate(8);
    rsx! { div { class: "pc2-analysis-grid performance",
        AnalysisCard { title: "Latency distribution", subtitle: "Fixed buckets keep runs directly comparable",
            LatencyHistogram { buckets: analysis.latency_histogram.clone() }
        }
        AnalysisCard { title: "Percentile profile", subtitle: "Observed samples only",
            div { class: "pc2-percentiles",
                Percentile { label: "P50", value: analysis.latency_ms.p50, max: analysis.latency_ms.max }
                Percentile { label: "P95", value: analysis.latency_ms.p95, max: analysis.latency_ms.max }
                Percentile { label: "Max", value: analysis.latency_ms.max, max: analysis.latency_ms.max }
                div { class: "pc2-percentile-coverage", "Latency {analysis.latency_ms.sample_count}/{analysis.latency_ms.total_count} · TTFT {analysis.ttft_ms.sample_count}/{analysis.ttft_ms.total_count}" }
            }
        }
        article { class: "pc2-analysis-card wide",
            header { div { h3 { "Latency by step" } p { "Ordered by sequence and normalized to the slowest loaded step · select a bar for details" } } }
            TurnMetricChart { turns: turns.clone(), metric: "latency", on_turn }
        }
        article { class: "pc2-analysis-card wide",
            header { div { h3 { "Slowest steps" } p { "Highest observed end-to-end latency among the loaded steps" } } }
            div { class: "pc2-ranked-list",
                if slowest.is_empty() { EmptyAnalysis { label: "No latency samples by step" } }
                for (index, (turn, latency)) in slowest.into_iter().enumerate() {
                    button { onclick: move |_| on_turn.call(turn.id),
                        span { class: "pc2-rank", "{index + 1}" }
                        span { class: "pc2-ranked-copy", strong { "Step #{turn.id} · {turn.source}" } small { "{short(&turn.preview, 100)}" } }
                        code { "{format_ms(latency)}" }
                    }
                }
            }
        }
    } }
}

#[component]
fn TokenAnalysis(
    analysis: RunAnalysis,
    turns: Vec<TurnSummary>,
    on_turn: EventHandler<i64>,
) -> Element {
    let prompt = analysis.prompt_tokens.unwrap_or_default();
    let completion = analysis.completion_tokens.unwrap_or_default();
    let total = analysis
        .total_tokens
        .unwrap_or_default()
        .max(prompt.saturating_add(completion));
    let prompt_width = percent(prompt as f64, total as f64);
    let completion_width = percent(completion as f64, total as f64);
    rsx! { div { class: "pc2-analysis-grid tokens",
        article { class: "pc2-analysis-card wide pc2-token-composition",
            header { div { h3 { "Token composition" } p { "Captured prompt and completion usage across the run" } } strong { "{optional_u64(analysis.total_tokens)} total" } }
            div { class: "pc2-token-track", title: "Prompt {prompt} · Completion {completion}",
                i { class: "prompt", style: "width:{prompt_width}%" }
                i { class: "completion", style: "width:{completion_width}%" }
            }
            div { class: "pc2-token-legend", span { i { class: "prompt" } "Prompt {prompt}" } span { i { class: "completion" } "Completion {completion}" } }
        }
        article { class: "pc2-analysis-card wide",
            header { div { h3 { "Tokens by step" } p { "Prompt and completion tokens · select a bar for details" } } }
            TurnMetricChart { turns: turns.clone(), metric: "tokens", on_turn }
        }
        AnalysisCard { title: "Tokens by source", subtitle: "Full-run aggregate by captured source",
            TokenDimensionBars { items: analysis.source_breakdown.clone() }
        }
        AnalysisCard { title: "Tokens by model", subtitle: "Full-run aggregate by attributed model",
            TokenDimensionBars { items: analysis.model_breakdown.clone() }
        }
    } }
}

#[component]
fn ToolAnalysis(tools: Vec<ToolAggregate>) -> Element {
    let mut tools = tools;
    tools.sort_by_key(|tool| std::cmp::Reverse(tool.count));
    let max_count = tools.iter().map(|tool| tool.count).max().unwrap_or(0);
    rsx! { div { class: "pc2-analysis-grid tools",
        article { class: "pc2-analysis-card wide",
            header { div { h3 { "Tool performance" } p { "Frequency, observed duration, and association with steps that reported errors" } } span { "{tools.len()} tools" } }
            div { class: "pc2-tool-table",
                div { class: "pc2-tool-head", span { "Tool" } span { "Calls" } span { "Observed duration" } span { "Average" } span { "Max" } span { "Error-linked" } }
                if tools.is_empty() { EmptyAnalysis { label: "No tool calls captured" } }
                for tool in tools {
                    div { class: "pc2-tool-row",
                        div { strong { "{tool.name}" } span { class: "pc2-mini-track", i { style: format!("width:{}%", percent(tool.count as f64, max_count as f64)) } } }
                        code { "{tool.count}" }
                        code { "{tool.duration_sample_count}/{tool.count}" }
                        code { {tool.average_duration_ms.map(format_ms).unwrap_or_else(|| "—".into())} }
                        code { {tool.max_duration_ms.map(format_ms).unwrap_or_else(|| "—".into())} }
                        span { class: if tool.error_associated_count > 0 { "pc2-tool-errors active" } else { "pc2-tool-errors" }, "{tool.error_associated_count}" }
                    }
                }
            }
        }
    } }
}

#[component]
fn AnalysisCard(title: &'static str, subtitle: &'static str, children: Element) -> Element {
    rsx! { article { class: "pc2-analysis-card", header { div { h3 { "{title}" } p { "{subtitle}" } } } {children} } }
}

#[component]
fn DimensionBars(items: Vec<DimensionAggregate>, tone: &'static str) -> Element {
    let max = items.iter().map(|item| item.turn_count).max().unwrap_or(0);
    rsx! { div { class: "pc2-dimension-list {tone}",
        if items.is_empty() { EmptyAnalysis { label: "No values captured" } }
        for item in items {
            div { class: "pc2-dimension-row",
                div { span { title: "{item.name}", "{item.name}" } code { "{item.turn_count}" } }
                span { class: "pc2-dimension-track", i { style: format!("width:{}%", percent(item.turn_count as f64, max as f64)) } }
                small { {format!("{} errors · {}", item.error_count, item.average_latency_ms.map(format_ms).unwrap_or_else(|| "no latency".into()))} }
            }
        }
    } }
}

#[component]
fn TokenDimensionBars(items: Vec<DimensionAggregate>) -> Element {
    let max = items
        .iter()
        .filter_map(|item| item.total_tokens)
        .max()
        .unwrap_or(0);
    rsx! { div { class: "pc2-dimension-list amber",
        if max == 0 { EmptyAnalysis { label: "No token attribution captured" } }
        for item in items.into_iter().filter(|item| item.total_tokens.is_some()) {
            div { class: "pc2-dimension-row",
                div { span { title: "{item.name}", "{item.name}" } code { {item.total_tokens.unwrap_or_default().to_string()} } }
                span { class: "pc2-dimension-track", i { style: format!("width:{}%", percent(item.total_tokens.unwrap_or_default() as f64, max as f64)) } }
                small { "Across {item.turn_count} steps" }
            }
        }
    } }
}

#[component]
fn CoverageRow(label: &'static str, observed: usize, total: usize) -> Element {
    let coverage = percent(observed as f64, total as f64);
    rsx! { div { div { span { "{label}" } code { "{observed}/{total}" } } span { class: "pc2-coverage-track", i { style: "width:{coverage}%" } } } }
}

#[component]
fn LatencyHistogram(buckets: Vec<HistogramBucket>) -> Element {
    let max = buckets.iter().map(|bucket| bucket.count).max().unwrap_or(0);
    rsx! { div { class: "pc2-histogram",
        for bucket in buckets {
            div { class: "pc2-histogram-column", title: format!("{}: {} samples", bucket.label, bucket.count),
                span { "{bucket.count}" }
                div { i { style: format!("height:{}%", percent(bucket.count as f64, max as f64)) } }
                small { "{bucket.label}" }
            }
        }
    } }
}

#[component]
fn Percentile(label: &'static str, value: Option<f64>, max: Option<f64>) -> Element {
    let width = percent(value.unwrap_or_default(), max.unwrap_or_default());
    rsx! { div { class: "pc2-percentile", div { span { "{label}" } code { {value.map(format_ms).unwrap_or_else(|| "—".into())} } } span { i { style: "width:{width}%" } } } }
}

#[component]
fn TurnMetricChart(
    turns: Vec<TurnSummary>,
    metric: &'static str,
    on_turn: EventHandler<i64>,
) -> Element {
    let visible = sampled_turns(&turns, 120);
    let max = visible
        .iter()
        .filter_map(|turn| turn_metric(turn, metric))
        .fold(0.0f64, f64::max);
    rsx! { div { class: "pc2-turn-chart",
        if max <= 0.0 {
            if metric == "tokens" { EmptyAnalysis { label: "No token samples by step" } }
            else { EmptyAnalysis { label: "No latency samples by step" } }
        }
        else { div { class: "pc2-turn-bars",
            for turn in visible {
                button { aria_label: "Open step {turn.id}", title: format!("Step #{} · {} · {}", turn.id, turn.source, metric_value(&turn, metric)), onclick: move |_| on_turn.call(turn.id),
                    i { class: "{turn.source}", style: format!("height:{}%", percent(turn_metric(&turn, metric).unwrap_or_default(), max)) }
                }
            }
        } }
        if turns.len() > 120 { p { class: "pc2-chart-note", "Showing an even sample of 120 from {turns.len()} loaded steps" } }
    } }
}

#[component]
fn EmptyAnalysis(label: &'static str) -> Element {
    rsx! { div { class: "pc2-analysis-empty", "{label}" } }
}

// Keep the legacy key so existing browser preferences survive the UI rename.
const ASSISTANT_WIDE_KEY: &str = "pchronicle_copilot_wide";

fn load_copilot_wide() -> bool {
    web_sys::window()
        .and_then(|window| window.local_storage().ok().flatten())
        .and_then(|storage| storage.get_item(ASSISTANT_WIDE_KEY).ok().flatten())
        .map(|value| value == "1" || value.eq_ignore_ascii_case("true"))
        .unwrap_or(false)
}

fn save_copilot_wide(wide: bool) {
    let Some(window) = web_sys::window() else {
        return;
    };
    let Some(storage) = window.local_storage().ok().flatten() else {
        return;
    };
    let _ = storage.set_item(ASSISTANT_WIDE_KEY, if wide { "1" } else { "0" });
}

fn assistant_panel_class(wide: bool) -> &'static str {
    if wide {
        "pc2-copilot wide"
    } else {
        "pc2-copilot"
    }
}

const ASSISTANT_CHAT_ID: &str = "pc2-copilot-chat";
const COPILOT_FOLLOW_THRESHOLD: f64 = 48.0;

fn copilot_distance_from_bottom(scroll_top: f64, client_height: f64, scroll_height: f64) -> f64 {
    (scroll_height - client_height - scroll_top).max(0.0)
}

fn copilot_is_near_bottom(scroll_top: f64, client_height: f64, scroll_height: f64) -> bool {
    copilot_distance_from_bottom(scroll_top, client_height, scroll_height)
        <= COPILOT_FOLLOW_THRESHOLD
}

fn copilot_following_after_scroll(following: bool, near_bottom: bool) -> bool {
    following && near_bottom
}

fn copilot_chat_element() -> Option<web_sys::Element> {
    web_sys::window()?
        .document()?
        .get_element_by_id(ASSISTANT_CHAT_ID)
}

fn copilot_chat_is_near_bottom() -> bool {
    let Some(element) = copilot_chat_element() else {
        return true;
    };
    copilot_is_near_bottom(
        f64::from(element.scroll_top()),
        f64::from(element.client_height()),
        f64::from(element.scroll_height()),
    )
}

fn scroll_copilot_chat_to_bottom() {
    let Some(element) = copilot_chat_element() else {
        return;
    };
    element.set_scroll_top(element.scroll_height());
}

#[component]
fn AssistantWideToggle(wide: bool, on_toggle: EventHandler<MouseEvent>) -> Element {
    rsx! {
        button {
            class: "pc2-copilot-wide-toggle",
            aria_label: if wide { "Restore Assistant width" } else { "Expand Assistant to two-thirds width" },
            title: if wide { "Restore Assistant width" } else { "Expand Assistant to two-thirds of the screen" },
            aria_pressed: wide,
            onclick: on_toggle,
            if wide { "⤡" } else { "⤢" }
        }
    }
}

#[component]
fn AssistantPanel(
    run: Option<RunSummary>,
    analysis: Option<RunAnalysis>,
    turns: Vec<TurnSummary>,
    selected: Option<TurnDetail>,
    wide: bool,
    on_toggle_wide: EventHandler<MouseEvent>,
    on_close: EventHandler<MouseEvent>,
    on_turn: EventHandler<i64>,
    on_open_session: EventHandler<AssistantSessionMeta>,
) -> Element {
    let mut index = use_signal(|| load_index(&BrowserStore));
    let mut session_id = use_signal(|| None::<String>);
    let mut bound_query = use_signal(|| None::<String>);
    let mut thread = use_signal(empty_thread);
    let mut input = use_signal(String::new);
    let mut busy = use_signal(|| false);
    let mut settings = use_signal(|| false);
    let mut history_open = use_signal(|| false);
    let mut config = use_signal(llm::load_config);
    let mut step = use_signal(|| "Working…".to_string());
    let mut following = use_signal(|| true);
    let run_for_effect = run.clone();
    use_effect(move || {
        let Some(current) = run_for_effect.clone() else {
            return;
        };
        let query = current.query();
        if Some(query.clone()) == bound_query() {
            return;
        }
        bound_query.set(Some(query));
        let now = now_millis();
        let (next_index, id, next_thread) =
            restore_for_run(&BrowserStore, &current, &new_session_id(now), now);
        index.set(next_index);
        session_id.set(id);
        thread.set(next_thread);
    });
    let focused_turn_id = selected.as_ref().map(|detail| detail.summary.id);
    let update_step = Callback::new(move |next: String| step.set(next));
    let submit_run = run.clone();
    let submit_analysis = analysis.clone();
    let submit_copilot = Callback::new(move |()| {
        let question = input().trim().to_string();
        let Some(submit_run) = submit_run.clone() else {
            return;
        };
        let Some(submit_analysis) = submit_analysis.clone() else {
            return;
        };
        if question.is_empty() || busy() {
            return;
        }
        let config_value = config();
        if !config_value.is_configured() {
            const CONFIGURE_MESSAGE: &str =
                "Configure an OpenAI-compatible model in Settings before asking Assistant.";
            settings.set(true);
            let mut next_thread = thread();
            let already_shown = next_thread.messages.last().is_some_and(|message| {
                message.role == ThreadRole::Assistant && message.text == CONFIGURE_MESSAGE
            });
            if !already_shown {
                next_thread.messages.push(ThreadMessage {
                    role: ThreadRole::Assistant,
                    text: CONFIGURE_MESSAGE.into(),
                    tool_calls: None,
                    tool_call_id: None,
                    tool_name: None,
                    sql: None,
                    truncated: false,
                    reasoning_content: None,
                });
                thread.set(next_thread);
            }
            return;
        }

        let prior_thread = thread();
        let mut pending_thread = prior_thread.clone();
        pending_thread.messages.push(ThreadMessage {
            role: ThreadRole::User,
            text: question.clone(),
            tool_calls: None,
            tool_call_id: None,
            tool_name: None,
            sql: None,
            truncated: false,
            reasoning_content: None,
        });
        thread.set(pending_thread.clone());
        input.set(String::new());
        step.set("Working…".into());
        following.set(true);
        busy.set(true);
        spawn(async move {
            let report_step = |next: &str| update_step.call(next.to_string());
            let result = agent::answer(agent::AnswerRequest {
                config: &config_value,
                user_message: &question,
                run: &submit_run,
                analysis: &submit_analysis,
                focused_turn_id,
                thread: prior_thread,
                on_step: Some(&report_step),
            })
            .await;
            let finished = match result {
                Ok(answer) => answer.thread,
                Err(message) => {
                    pending_thread.messages.push(ThreadMessage {
                        role: ThreadRole::Assistant,
                        text: format!("Unable to complete analysis: {message}"),
                        tool_calls: None,
                        tool_call_id: None,
                        tool_name: None,
                        sql: None,
                        truncated: false,
                        reasoning_content: None,
                    });
                    pending_thread
                }
            };
            let now = now_millis();
            let id = session_id().unwrap_or_else(|| new_session_id(now));
            session_id.set(Some(id.clone()));
            let mut next_index = index();
            persist_indexed_thread(
                &BrowserStore,
                &mut next_index,
                &id,
                &submit_run,
                &finished,
                now,
            );
            index.set(next_index);
            thread.set(finished);
            busy.set(false);
        });
    });
    use_effect(move || {
        let _len = thread().messages.len();
        let _busy = busy();
        let _step = step();
        if following() {
            scroll_copilot_chat_to_bottom();
        }
    });
    let title = title_from_thread(&thread());
    let new_chat_enabled = can_start_new_chat(run.is_some(), &thread()) && !busy();
    let context_line = match (&run, &analysis, selected.as_ref()) {
        (None, _, _) => "Open a run to start a chat.".to_string(),
        (Some(_), None, _) => "Loading run details…".to_string(),
        (Some(_), Some(_), Some(detail)) => format!("Step {} in context", detail.summary.id),
        (Some(_), Some(_), None) => "Current run in context".to_string(),
    };
    let composer_enabled = run.is_some() && analysis.is_some() && !busy();
    let sessions = index().sessions;
    rsx! { aside { class: assistant_panel_class(wide),
        div { class: "pc2-copilot-head",
            div { class: "pc2-copilot-head-title", strong { "{title}" } span { "Read-only · selected run data" } }
            div { class: "pc2-copilot-actions",
                button {
                    aria_label: "New chat",
                    title: "New chat",
                    disabled: !new_chat_enabled,
                    onclick: move |_| {
                        if !new_chat_enabled { return; }
                        session_id.set(None);
                        thread.set(empty_thread());
                        history_open.set(false);
                    },
                    "+"
                }
                button {
                    aria_label: "Chat history",
                    title: "Chat history",
                    aria_pressed: history_open(),
                    disabled: busy(),
                    onclick: move |_| history_open.set(!history_open()),
                    "◷"
                }
                button { aria_label: "LLM settings", onclick: move |_| settings.set(true), "⚙" }
                AssistantWideToggle { wide, on_toggle: on_toggle_wide }
                button { aria_label: "Close Assistant", onclick: on_close, "×" }
            }
        }
        if history_open() {
            div { class: "pc2-copilot-history", role: "listbox", aria_label: "Assistant history",
                if sessions.is_empty() {
                    div { class: "pc2-copilot-history-empty", "No saved chats yet." }
                }
                for meta in sessions.iter().cloned() {
                    {
                        let active = session_id().as_deref() == Some(meta.id.as_str());
                        let row = meta.clone();
                        let delete_id = meta.id.clone();
                        rsx! {
                            div { class: if active { "pc2-copilot-history-row active" } else { "pc2-copilot-history-row" },
                                button {
                                    r#type: "button",
                                    class: "pc2-copilot-history-open",
                                    onclick: move |_| {
                                        if busy() { return; }
                                        let loaded = load_session_thread(&BrowserStore, &row.id);
                                        session_id.set(Some(row.id.clone()));
                                        thread.set(loaded);
                                        bound_query.set(Some(row.run.query()));
                                        history_open.set(false);
                                        following.set(true);
                                        on_open_session.call(row.clone());
                                    },
                                    strong { "{meta.title}" }
                                    span { "{short(&meta.run.session_id, 18)} · {relative_time(now_millis(), meta.updated_at)}" }
                                }
                                button {
                                    r#type: "button",
                                    class: "pc2-copilot-history-delete",
                                    aria_label: "Delete chat",
                                    onclick: move |event| {
                                        event.stop_propagation();
                                        let mut next = index();
                                        let fallback = delete_session(&mut next, &delete_id);
                                        let store = BrowserStore;
                                        store.remove(&session_storage_key(&delete_id));
                                        save_index(&BrowserStore, &next);
                                        index.set(next);
                                        if session_id().as_deref() == Some(delete_id.as_str()) {
                                            if let Some(id) = fallback {
                                                session_id.set(Some(id.clone()));
                                                thread.set(load_session_thread(&BrowserStore, &id));
                                            } else {
                                                session_id.set(None);
                                                thread.set(empty_thread());
                                            }
                                        }
                                    },
                                    "×"
                                }
                            }
                        }
                    }
                }
            }
        }
        div { class: "pc2-chat-wrap",
            div {
                id: ASSISTANT_CHAT_ID,
                class: "pc2-chat",
                onscroll: move |_| {
                    following.set(copilot_following_after_scroll(following(), copilot_chat_is_near_bottom()));
                },
                if thread().messages.is_empty() {
                    div { class: "pc2-chat-welcome", span { "◇" } strong { "Ask Assistant" }
                        if run.is_none() {
                            p { "Open a run, or select a previous chat from history." }
                        } else if config().is_configured() {
                            p { "Assistant can inspect this analysis, examine a step, or run read-only SQL." }
                        } else {
                            p { "Configure an OpenAI-compatible model in Settings before asking Assistant." }
                        }
                    }
                }
                for (index, message) in thread().messages.iter().enumerate() {
                    if !(message.role == ThreadRole::Assistant
                        && message.text.trim().is_empty()
                        && message.tool_calls.as_ref().is_some_and(|calls| !calls.is_empty()))
                    {
                        ChatBubble { key: "message-{index}", message: message.clone(), turns: turns.clone(), on_turn }
                    }
                }
                if busy() { div { class: "pc2-chat-working", span { class: "spinner" } "{step}" } }
            }
            if !thread().messages.is_empty() || busy() {
                if following() {
                    button {
                        class: "pc2-chat-follow",
                        r#type: "button",
                        aria_pressed: "true",
                        title: "Stop following new output",
                        aria_label: "Stop following new output",
                        onclick: move |_| following.set(false),
                        "Following"
                    }
                } else {
                    button {
                        class: "pc2-chat-follow jump",
                        r#type: "button",
                        title: "Jump to latest output and follow",
                        aria_label: "Jump to latest output and follow",
                        onclick: move |_| {
                            following.set(true);
                            scroll_copilot_chat_to_bottom();
                        },
                        "↓ Latest"
                    }
                }
            }
        }
        form { class: "pc2-composer pc2-composer-compact", onsubmit: move |event| { event.prevent_default(); submit_copilot.call(()); },
            textarea {
                value: "{input}",
                rows: "2",
                placeholder: if run.is_none() { "Open a run to start a chat…" } else if analysis.is_none() { "Loading run details…" } else { "Ask about this run…" },
                oninput: move |event| input.set(event.value()),
                onkeydown: move |event| if event.key() == Key::Enter && !event.modifiers().shift() { event.prevent_default(); submit_copilot.call(()); },
                disabled: !composer_enabled
            }
            button { class: "button primary", disabled: !composer_enabled || input().trim().is_empty(), "Send" }
        }
        div { class: "pc2-composer-context", "{context_line}" }
        if settings() { LlmSettings { config: config(), on_close: move |_| settings.set(false), on_save: move |value| { llm::save_config(&value); config.set(value); settings.set(false); } } }
    } }
}
#[component]
fn ChatBubble(
    message: ThreadMessage,
    turns: Vec<TurnSummary>,
    on_turn: EventHandler<i64>,
) -> Element {
    let message = if message.role == ThreadRole::Assistant {
        match agent::visible_assistant_text(&message.text) {
            None => return rsx! {},
            Some(text) => ThreadMessage { text, ..message },
        }
    } else {
        message
    };
    if message.role == ThreadRole::Tool {
        let action = message
            .tool_name
            .clone()
            .unwrap_or_else(|| "tool".to_string());
        return rsx! {
            div { class: "pc2-message tool",
                span { class: "pc2-action-label", "Running {action} ›" }
                if !message.text.trim().is_empty() {
                    details { summary { "Tool output" } pre { "{message.text}" } }
                }
            }
        };
    }
    let refs = turn_references(&message.text);
    let blocks = parse_rich_blocks(&message.text);
    rsx! { div { class: if message.role == ThreadRole::User { "pc2-message user" } else { "pc2-message assistant" },
        for (index, block) in blocks.into_iter().enumerate() {
            match block {
                RichBlock::Text(text) => rsx! { MessageText { key: "text-{index}", text } },
                RichBlock::Table(table) => rsx! { DataTable { key: "table-{index}", evidence: table.evidence, title: table.title, embedded: true } },
                RichBlock::Trajectory(trajectory) => {
                    let visible = turns.iter().filter(|turn| trajectory.turn_ids.contains(&turn.id)).cloned().collect::<Vec<_>>();
                    rsx! { div { key: "trajectory-{index}", class: "pc2-chat-component",
                        if let Some(title) = trajectory.title { strong { class: "pc2-chat-component-title", "{title}" } }
                        if visible.is_empty() { div { class: "pc2-data-empty", "Referenced steps are outside the loaded data window." } }
                        else { TrajectoryView { turns: visible, expanded_turn_id: None, detail: None, loading: false, embedded: true, view: "steps".to_string(), on_turn } }
                    } }
                },
            }
        }
        if let Some(sql) = &message.sql { details { class: "pc2-message-sql", summary { "Executed read-only SQL" } pre { "{sql}" } } }
        if message.truncated { div { class: "pc2-truncated", "The available data was limited or truncated; conclusions may be incomplete." } }
        if !refs.is_empty() { div { class: "pc2-citations", for id in refs { button { onclick: move |_| on_turn.call(id), "Step #{id}" } } } }
    } }
}

#[component]
fn MessageText(text: String) -> Element {
    rsx! { div { class: "pc2-message-text", for line in text.lines() { if let Some(item) = line.strip_prefix("- ") { div { class: "pc2-bullet", span { "•" } p { "{clean_markdown(item)}" } } } else if !line.trim().is_empty() { p { "{clean_markdown(line)}" } } } } }
}

fn short(value: &str, limit: usize) -> String {
    if value.chars().count() <= limit {
        value.into()
    } else {
        format!(
            "{}…",
            value
                .chars()
                .take(limit.saturating_sub(1))
                .collect::<String>()
        )
    }
}

fn format_ms(value: f64) -> String {
    if value >= 1000.0 {
        format!("{:.2}s", value / 1000.0)
    } else {
        format!("{value:.1}ms")
    }
}
fn optional_u64(value: Option<u64>) -> String {
    value
        .map(|value| value.to_string())
        .unwrap_or_else(|| "—".into())
}

#[derive(Clone, Debug, PartialEq)]
struct MixSegment {
    name: String,
    count: usize,
    share: f64,
}

#[derive(Clone, Debug, PartialEq)]
struct CoveragePoint {
    label: &'static str,
    observed: usize,
    total: usize,
}

fn compact_mix(items: &[DimensionAggregate], limit: usize) -> Vec<MixSegment> {
    let total: usize = items.iter().map(|item| item.turn_count).sum();
    if total == 0 || limit == 0 {
        return Vec::new();
    }
    let mut ranked = items.to_vec();
    ranked.sort_by(|left, right| right.turn_count.cmp(&left.turn_count));
    let mut segments: Vec<MixSegment> = ranked
        .iter()
        .take(limit)
        .map(|item| MixSegment {
            name: item.name.clone(),
            count: item.turn_count,
            share: percent(item.turn_count as f64, total as f64),
        })
        .collect();
    let rest: usize = ranked.iter().skip(limit).map(|item| item.turn_count).sum();
    if rest > 0 {
        segments.push(MixSegment {
            name: "other".into(),
            count: rest,
            share: percent(rest as f64, total as f64),
        });
    }
    if !segments.is_empty() {
        let used: f64 = segments
            .iter()
            .rev()
            .skip(1)
            .map(|segment| segment.share)
            .sum();
        if let Some(last) = segments.last_mut() {
            last.share = (100.0 - used).clamp(0.0, 100.0);
        }
    }
    segments
}

fn coverage_points(
    latency_observed: usize,
    latency_total: usize,
    ttft_observed: usize,
    ttft_total: usize,
    timestamp_observed: usize,
    timestamp_total: usize,
    token_observed: usize,
    token_total: usize,
) -> Vec<CoveragePoint> {
    vec![
        CoveragePoint {
            label: "Latency",
            observed: latency_observed,
            total: latency_total,
        },
        CoveragePoint {
            label: "TTFT",
            observed: ttft_observed,
            total: ttft_total,
        },
        CoveragePoint {
            label: "Timestamp",
            observed: timestamp_observed,
            total: timestamp_total,
        },
        CoveragePoint {
            label: "Tokens",
            observed: token_observed,
            total: token_total,
        },
    ]
}

fn mix_title(segments: &[MixSegment]) -> String {
    segments
        .iter()
        .map(|segment| format!("{} {}", segment.name, segment.count))
        .collect::<Vec<_>>()
        .join(" · ")
}

fn percent(value: f64, total: f64) -> f64 {
    if !value.is_finite() || !total.is_finite() || total <= 0.0 {
        0.0
    } else {
        (value / total * 100.0).clamp(0.0, 100.0)
    }
}
fn sampled_turns(turns: &[TurnSummary], limit: usize) -> Vec<TurnSummary> {
    if turns.len() <= limit || limit < 2 {
        return turns.to_vec();
    }
    (0..limit)
        .map(|index| index * (turns.len() - 1) / (limit - 1))
        .map(|index| turns[index].clone())
        .collect()
}
fn turn_metric(turn: &TurnSummary, metric: &str) -> Option<f64> {
    match metric {
        "tokens" => turn.total_tokens.map(|value| value as f64),
        _ => turn.latency_ms,
    }
}
fn metric_value(turn: &TurnSummary, metric: &str) -> String {
    match metric {
        "tokens" => turn
            .total_tokens
            .map(|value| format!("{value} tokens"))
            .unwrap_or_else(|| "no token sample".into()),
        _ => turn
            .latency_ms
            .map(format_ms)
            .unwrap_or_else(|| "no latency sample".into()),
    }
}
fn clean_markdown(value: &str) -> String {
    value.replace("**", "").replace('`', "")
}
fn turn_references(value: &str) -> Vec<i64> {
    let mut ids = Vec::new();
    let mut rest = value;
    while let Some((_, next)) = rest.split_once("[turn:") {
        if let Some((raw, after)) = next.split_once(']') {
            if let Ok(id) = raw.parse() {
                if !ids.contains(&id) {
                    ids.push(id);
                }
            }
            rest = after;
        } else {
            break;
        }
    }
    ids
}

fn url_param(name: &str) -> Option<String> {
    let search = web_sys::window()?.location().search().ok()?;
    web_sys::UrlSearchParams::new_with_str(&search)
        .ok()?
        .get(name)
}

fn analyze_workspace_url(session_id: &str) -> String {
    if session_id.is_empty() {
        "/?page=tools".into()
    } else {
        format!(
            "/?page=tools&analysis_session={}",
            urlencoding::encode(session_id)
        )
    }
}

fn analysis_url_sync_target(session_id: &str, seed_scope_pending: bool) -> Option<String> {
    if seed_scope_pending && session_id.is_empty() {
        None
    } else {
        Some(analyze_workspace_url(session_id))
    }
}

fn run_analysis_scope(
    catalog: &QueryCatalog,
    run: RunSummary,
) -> crate::analysis_session::AnalysisScope {
    crate::analysis_session::AnalysisScope::from_run(catalog, run)
}

#[allow(clippy::too_many_arguments)]
fn sync_workspace_url(
    page: &str,
    analysis_session_id: &str,
    analysis_seed_scope_pending: bool,
    run: Option<&RunSummary>,
    query: &str,
    dataset_filter: &str,
    status: &str,
    sort: &str,
    direction: &str,
    path: &str,
    file_prefix: &str,
    workspace: &str,
    view: &str,
    source: &str,
    turn_query: &str,
    turn_id: Option<i64>,
) {
    let Some(window) = web_sys::window() else {
        return;
    };
    if page == "tools" {
        let Some(url) = analysis_url_sync_target(analysis_session_id, analysis_seed_scope_pending)
        else {
            return;
        };
        let _ = window
            .history()
            .and_then(|history| history.replace_state_with_url(&JsValue::NULL, "", Some(&url)));
        return;
    }
    if page == "physical" {
        return;
    }
    let mut params = vec![format!("page={}", urlencoding::encode(page))];
    if let Some(run) = run.filter(|_| page == "detail") {
        params.push(format!("dataset={}", urlencoding::encode(&run.dataset)));
        params.push(format!("file={}", urlencoding::encode(&run.file)));
        if let Some(run_id) = run.run_id.as_deref().filter(|value| !value.is_empty()) {
            params.push(format!("run_id={}", urlencoding::encode(run_id)));
        }
        params.push(format!("agent_id={}", urlencoding::encode(&run.agent_id)));
        params.push(format!(
            "session_id={}",
            urlencoding::encode(&run.session_id)
        ));
        if let Some(root) = &run.root_session_id {
            params.push(format!("root_session_id={}", urlencoding::encode(root)));
        }
        params.push(format!("workspace={}", urlencoding::encode(workspace)));
        params.push(format!("view={}", urlencoding::encode(view)));
        params.push(format!("source={}", urlencoding::encode(source)));
        if !turn_query.is_empty() {
            params.push(format!("turn_q={}", urlencoding::encode(turn_query)));
        }
        if let Some(turn_id) = turn_id {
            params.push(format!("turn={turn_id}"));
        }
    } else if page == "runs" {
        if !query.is_empty() {
            params.push(format!("q={}", urlencoding::encode(query)));
        }
        params.push(format!("status={}", urlencoding::encode(status)));
        if dataset_filter != "all" {
            params.push(format!(
                "dataset_filter={}",
                urlencoding::encode(dataset_filter)
            ));
        }
        params.push(format!("sort={}", urlencoding::encode(sort)));
        params.push(format!("direction={}", urlencoding::encode(direction)));
        if !path.is_empty() {
            params.push(format!("path={}", urlencoding::encode(path)));
        }
        if !file_prefix.is_empty() {
            params.push(format!("file_prefix={}", urlencoding::encode(file_prefix)));
        }
    }
    let url = format!("/?{}", params.join("&"));
    let _ = window
        .history()
        .and_then(|history| history.replace_state_with_url(&JsValue::NULL, "", Some(&url)));
}

#[cfg(test)]
mod tests {
    use super::*;

    fn run_at(path: &str) -> RunSummary {
        RunSummary {
            dataset: "dataset".into(),
            file: ".".into(),
            run_id: Some(path.rsplit('/').next().unwrap_or_default().into()),
            agent_id: "agent".into(),
            model_name: None,
            session_id: path.rsplit('/').next().unwrap_or_default().into(),
            root_session_id: Some("root".into()),
            path: path.into(),
            row_count: 1,
            duplicate_event_ids: 0,
            status: "completed".into(),
        }
    }

    #[test]
    fn assistant_panel_class_marks_expanded_width() {
        assert_eq!(assistant_panel_class(false), "pc2-copilot");
        assert_eq!(assistant_panel_class(true), "pc2-copilot wide");
    }

    #[test]
    fn copilot_follow_stays_on_near_the_bottom() {
        assert!(copilot_is_near_bottom(100.0, 400.0, 500.0));
        assert!(copilot_is_near_bottom(52.0, 400.0, 500.0));
        assert!(!copilot_is_near_bottom(0.0, 400.0, 800.0));
        assert!(copilot_following_after_scroll(true, true));
        assert!(!copilot_following_after_scroll(true, false));
        assert!(!copilot_following_after_scroll(false, true));
    }

    #[test]
    fn citations_are_unique_and_ordered() {
        assert_eq!(
            turn_references("see [turn:3], [turn:1], [turn:3]"),
            vec![3, 1]
        );
    }

    #[test]
    fn path_tree_preserves_hierarchy_and_subtree_counts() {
        let tree = build_path_tree(&[
            run_at("agent/root/session-a"),
            run_at("agent/root/subagents/session-b"),
        ]);
        let agent = tree.children.get("agent").unwrap();
        assert_eq!(subtree_run_count(agent), 2);
        assert!(agent.children["root"].children.contains_key("subagents"));
    }

    #[test]
    fn percent_handles_missing_and_caps_outliers() {
        assert_eq!(percent(25.0, 100.0), 25.0);
        assert_eq!(percent(10.0, 0.0), 0.0);
        assert_eq!(percent(150.0, 100.0), 100.0);
    }

    #[test]
    fn analyze_workspace_url_retains_only_the_session_id() {
        assert_eq!(
            analyze_workspace_url("analysis-123"),
            "/?page=tools&analysis_session=analysis-123"
        );
        assert_eq!(analyze_workspace_url(""), "/?page=tools");
    }

    #[test]
    fn bootstrap_scope_url_is_not_replaced_until_the_session_is_persisted() {
        assert_eq!(analysis_url_sync_target("", true), None);
        assert_eq!(
            analysis_url_sync_target("analysis-123", false),
            Some("/?page=tools&analysis_session=analysis-123".into())
        );
    }

    #[test]
    fn analyze_this_run_keeps_full_catalog_and_run_coordinates() {
        let run = run_at("agent/root/session-a");
        let catalog = QueryCatalog {
            snapshot_id: "snapshot-a".into(),
            read_only: true,
            database: "default".into(),
            storage_path: "/tmp/evidence".into(),
            path_column: "_file_".into(),
            datasets: Vec::new(),
            tables: Vec::new(),
        };

        let scope = run_analysis_scope(&catalog, run.clone());

        assert_eq!(scope.database, "default");
        assert_eq!(scope.storage_path, "/tmp/evidence");
        assert_eq!(scope.snapshot_id, "snapshot-a");
        assert_eq!(
            scope.items,
            vec![crate::analysis_session::AnalysisScopeItem::Run { run }]
        );
    }

    fn dim(name: &str, count: usize) -> DimensionAggregate {
        DimensionAggregate {
            name: name.into(),
            turn_count: count,
            error_count: 0,
            latency_sample_count: 0,
            average_latency_ms: None,
            total_tokens: None,
        }
    }

    #[test]
    fn compact_mix_keeps_small_breakdowns_intact() {
        let segments = compact_mix(&[dim("user", 43), dim("agent", 42), dim("system", 1)], 3);
        assert_eq!(
            segments
                .iter()
                .map(|segment| (segment.name.as_str(), segment.count))
                .collect::<Vec<_>>(),
            vec![("user", 43), ("agent", 42), ("system", 1)]
        );
        let share: f64 = segments.iter().map(|segment| segment.share).sum();
        assert!((share - 100.0).abs() < 0.01);
    }

    #[test]
    fn compact_mix_folds_the_tail_into_other() {
        let segments = compact_mix(
            &[
                dim("a", 10),
                dim("b", 8),
                dim("c", 6),
                dim("d", 3),
                dim("e", 1),
            ],
            3,
        );
        assert_eq!(
            segments
                .iter()
                .map(|segment| (segment.name.as_str(), segment.count))
                .collect::<Vec<_>>(),
            vec![("a", 10), ("b", 8), ("c", 6), ("other", 4)]
        );
    }

    #[test]
    fn compact_mix_ignores_empty_breakdowns() {
        assert!(compact_mix(&[], 3).is_empty());
        assert!(compact_mix(&[dim("user", 0)], 3).is_empty());
    }

    #[test]
    fn coverage_points_use_observed_over_total() {
        let points = coverage_points(42, 86, 8, 86, 84, 86, 42, 86);
        assert_eq!(
            points
                .iter()
                .map(|point| (point.label, point.observed, point.total))
                .collect::<Vec<_>>(),
            vec![
                ("Latency", 42, 86),
                ("TTFT", 8, 86),
                ("Timestamp", 84, 86),
                ("Tokens", 42, 86),
            ]
        );
    }

    #[test]
    fn evidence_notice_keeps_serde_details_collapsed() {
        let notice = evidence_notice(
            85,
            "invalid type: integer `1785310111`, expected a string at line 1 column 561",
        );
        assert_eq!(notice.title, "Step details could not be decoded");
        assert_eq!(
            notice.summary,
            "Step #85 · Expected string, received integer"
        );
        assert!(notice.detail.contains("1785310111"));
        assert_eq!(notice.turn_id, Some(85));
    }
}
