[application]
name = "pchronicle-web"
out_dir = "../crates/persisting-pchronicle-cli/web-assets"

[web]
pre_compress = true

[web.app]
title = "DeepTrace"
base_path = "/"

[web.dev]
hot_reload = true

[bundle]
public_url = "/"
base_path = "/"
